spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.165.2:3306/51html?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: '123456'
logging:
  level:
    com.website.center.*: debug
#  redis:
#    #        open: true  # 是否开启redis缓存  true开启   false关闭
#    database: 0
#    host: 47.98.165.2
#    port: 6379
#    password:       # 密码（默认为空）
#    timeout: 6000  # 连接超时时长（毫秒）
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接

#  devtools:
#    restart:
#      exclude: views/**,static/**
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#swagger:
#  base-package: com.distribution.modules.api.controller
#  enabled: true
#  title: API接口文档
#  description: API接口文档


